version: '3.1'

services:
  db:
    image: mariadb:11.7.2-noble
    restart: no
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=RootPassword
      - MARIADB_DATABASE=wordpress_db
      - MARIADB_USER=wordpressAdmin
      - MARIADB_PASSWORD=uberSafePassword
    ports:
      - 3306:3306

  wordpress:
    image: wordpress:6.7.2-php8.1-apache
    restart: no
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpressAdmin
      - WORDPRESS_DB_PASSWORD=uberSafePassword
      - WORDPRESS_DB_NAME=wordpress_db
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    restart: no
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db:3306
      - MYSQL_ROOT_PASSWORD=RootPassword
      - MYSQL_USER=wordpressAdmin
      - MYSQL_PASSWORD=uberSafePassword
    depends_on:
      - db

volumes:
  db_data:
  wp_data:
